import os
import re
import argparse
from pathlib import Path


def parse_filename(fname):
    """Parse the filenames generated by split.py.
    Format: <phonemes>_<SPEAKERID>_<SENTENCEID>_<start>_<end>.wav
    """
    fname = fname.replace(".wav", "")
    match = re.search(r"_([MF][A-Z]{3}[0-9])_([A-Z]{2}[0-9]+)_([0-9]+)_([0-9]+)$", fname)
    if match:
        speaker = match.group(1)
        sentence = match.group(2)
        start = int(match.group(3))
        end = int(match.group(4))
        return speaker, sentence, start, end
    return None, None, None, None


def reduce_dataset(paths, min_duration):
    """
    Reduce a list of wav paths:
      1. Drop SA sentences; A lot of duplicates that might over-represent certain phonemes
      2. Remove segments shorter than min_duration samples
      3. Keep only the longest segment per speaker+sentence for SI/SX
    """
    # Parse all paths
    records = []
    for path in paths:
        fname = os.path.basename(path)
        speaker, sentence, start, end = parse_filename(fname)
        if speaker is None:
            continue
        duration = end - start
        records.append({
            "path": path,
            "speaker": speaker,
            "sentence": sentence,
            "duration": duration,
            "sent_type": sentence[:2],
        })
 
    # Step 1: Drop SA sentences
    records = [r for r in records if r["sent_type"] != "SA"]
 
    # Step 2: Remove very short segments
    records = [r for r in records if r["duration"] >= min_duration]

    # Step 3: SI/SX - keep longest per speaker+sentence combo
    combo_best = {}
    for r in records:
        key = (r["speaker"], r["sentence"])
        if key not in combo_best or r["duration"] > combo_best[key]["duration"]:
            combo_best[key] = r
    reduced = list(combo_best.values())
 
    return [r["path"] for r in reduced]



def main():
    parser = argparse.ArgumentParser(
        description="Generate a TSV file of paths to split TIMIT wav files, optionally reduced"
    )
    parser.add_argument(
        "-d", required=True,
        help="Path to the directory with the wav files"
    )
    parser.add_argument(
        "--reduce", action="store_true",
        help="Reduce the files used; remove SA sentences, short segments and reduce SI/SX by longest of speaker+sentence"
    )
    parser.add_argument( # 500 for voiced, 200 for unvoiced
        "--min_duration", type=int, default=500,
        help="Minimum segment duration in samples to keep (default: 500)."
    )

    args = parser.parse_args()
    directory = Path(args.d)

    paths = []
    for root, dirs, files in os.walk(directory):
        for file in files:
            if file.lower().endswith(".wav"):
                paths.append(os.path.join(root, file))

    print(f"Found {len(paths)} wav files in {directory}")

    if args.reduce:
        print(f"Reducing...")
        paths = reduce_dataset(paths, min_duration=args.min_duration)

    with open("train_paths.tsv", "w") as f:
        f.write("path_wav\n")
        for path in paths:
            f.write(f"{path}\n")

    print(f"Saved {len(paths)} paths to train_paths.tsv")


if __name__ == "__main__":
    main()